export const REQUEST_AUTHOR_LIST = 'REQUEST_AUTHOR_LIST';
export const REQUEST_AUTHOR_LIST_SUCCESS = 'REQUEST_AUTHOR_LIST_SUCCESS';
export const REQUEST_AUTHOR_LIST_ERROR = 'REQUEST_AUTHOR_LIST_ERROR';

export const REQUEST_POST_LIST = 'REQUEST_POST_LIST';
export const REQUEST_POST_LIST_SUCCESS = 'REQUEST_POST_LIST_SUCCESS';
export const REQUEST_POST_LIST_ERROR = 'REQUEST_POST_LIST_ERROR';

export const REQUEST_COMMENT_LIST = 'REQUEST_COMMENT_LIST';
export const REQUEST_COMMENT_LIST_SUCCESS = 'REQUEST_COMMENT_LIST_SUCCESS';
export const REQUEST_COMMENT_LIST_ERROR = 'REQUEST_COMMENT_LIST_ERROR';

export const REQUEST_LIKES_LIST = 'REQUEST_LIKES_LIST';
export const REQUEST_LIKES_LIST_SUCCESS = 'REQUEST_LIKES_LIST_SUCCESS';
export const REQUEST_LIKES_LIST_ERROR = 'REQUEST_LIKES_LIST_ERROR';

export const REQUEST_COMMENTS_BY_POST = 'REQUEST_COMMENTS_BY_POST';
export const REQUEST_COMMENTS_BY_POST_SUCCESS = 'REQUEST_COMMENTS_BY_POST_SUCCESS';
export const REQUEST_COMMENTS_BY_POST_ERROR = 'REQUEST_COMMENTS_BY_POST_ERROR';