export const REQUEST_AUTHOR_LIST = 'REQUEST_AUTHOR_LIST';
export const REQUEST_AUTHOR_LIST_SUCCESS = 'REQUEST_AUTHOR_LIST_SUCCESS';
export const REQUEST_AUTHOR_LIST_ERROR = 'REQUEST_AUTHOR_LIST_ERROR';
